[env:adafruit_metro_m0]
platform = atmelsam
board = adafruit_metro_m0
framework = arduino
lib_deps =
    khoih-prog/WiFiWebServer
    https://github.com/DFRobot/DFRobot_BMM350
lib_ignore = 
    Adafruit TinyUSB Library
monitor_speed = 9600
